version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: usmartpro-local-pg
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=calendar
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=calendar
    volumes:
      - ../../postgres/data:/var/lib/postgresql/data
      - ../migrations/initdb:/docker-entrypoint-initdb.d
