logger:
  level: debug
  file: stderr
http:
    host: "127.0.0.1"
    port: "8000"
grpc:
    host: "127.0.0.1"
    port: "8001"
storage:
  type: "base" #"memory"
  dsn: "postgresql://calendar:postgres@localhost:5432/calendar"
